spring:
  application:
    name: gateway-service
  mvc:
    log-request-details: true
  codec:
    log-request-details: true
  cloud:
    cloud:
      consul:
        host: localhost
        port: 8500
        discovery:
          enabled: true
          service-name: ${spring.application.name}
          instance-id: ${spring.application.name}-${random.value}

    gateway:
      server:
        webflux:
          routes:
            - id: account-service-route
              uri: lb://account-service:8080
              predicates:
                - Path=/accounts/**
              filters:
                - RewritePath=/accounts/?(?<segment>.*), /$\{segment}
            - id: cash-service-route
              uri: lb://cash-service:8080
              predicates:
                - Path=/cash/**
              filters:
                - RewritePath=/cash/?(?<segment>.*), /$\{segment}
            - id: exchange-service-route
              uri: lb://exchange-service:8080
              predicates:
                - Path=/exchange/**
              filters:
                - RewritePath=/exchange/?(?<segment>.*), /$\{segment}
            - id: notification-service-route
              uri: lb://notification-service:8080
              predicates:
                - Path=/notifications/**
              filters:
                - RewritePath=/notifications/?(?<segment>.*), /$\{segment}
            - id: transfer-service-route
              uri: lb://transfer-service:8080
              predicates:
                - Path=/transfer/**
              filters:
                - RewritePath=/transfer/?(?<segment>.*), /$\{segment}

logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE
