apiVersion: v2
name: bank-app
description: Микросервисное приложение "Банк"
type: application
version: 0.1.0
dependencies:
  - name: front-ui
    version: 0.1.0
    repository: "file://charts/front-ui"
  - name: account-service
    version: 0.1.0
    repository: "file://charts/account-service"
  - name: cash-service
    version: 0.1.0
    repository: "file://charts/cash-service"
  - name: notification-service
    version: 0.1.0
    repository: "file://charts/notification-service"
  - name: transfer-service
    version: 0.1.0
    repository: "file://charts/transfer-service"
  - name: postgre-db
    version: 0.1.0
    repository: "file://charts/postgre-db"
  - name: identity-provider
    version: 0.1.0
    repository: "file://charts/identity-provider"